import json
import os

OUTPUT_FILE = "EchoFind_Pro.ipynb"

# ------------------------------------------------------------------------------
# NOTEBOOK CONTENT
# ------------------------------------------------------------------------------

# CELL 1: SETUP
cell_1_source = [
    "# 🎵 EchoFind Pro: Self-Supervised Audio Search [COLAB EDITION]\n",
    "# ==============================================================\n",
    "# This notebook implements the FULL EchoFind pipeline optimized for Google Colab Pro.\n",
    "# \n",
    "# **Configuration:**\n",
    "# - **Model:** ResNet50 (Self-Supervised SimCLR)\n",
    "# - **Training:** 200 Epochs\n",
    "# - **Batch Size:** 128 (Adjust to 256/512 if using A100)\n",
    "# - **Precision:** Mixed Precision (AMP) enabled\n",
    "# - **Dataset:** FMA Small (8GB, 8000 tracks)\n",
    "\n",
    "print('🚀 Setting up EchoFind Environment...')\n",
    "!pip install -q torchaudio librosa soundfile pandas seaborn scikit-learn\n",
    "print('✅ Dependencies installed.')"
]

# CELL 2: DATA DOWNLOAD
cell_2_source = [
    "# 🔽 Download FMA Dataset \n",
    "# ========================\n",
    "import os\n",
    "import zipfile\n",
    "\n",
    "DATA_ROOT = './data'\n",
    "os.makedirs(DATA_ROOT, exist_ok=True)\n",
    "\n",
    "# URLs\n",
    "FMA_SMALL_URL = 'https://os.unil.cloud.switch.ch/fma/fma_small.zip'\n",
    "FMA_META_URL = 'https://os.unil.cloud.switch.ch/fma/fma_metadata.zip'\n",
    "\n",
    "def download_and_extract(url, target_dir):\n",
    "    filename = url.split('/')[-1]\n",
    "    path = os.path.join(target_dir, filename)\n",
    "    if not os.path.exists(path):\n",
    "        print(f'⬇️ Downloading {filename}...')\n",
    "        !wget -P {target_dir} {url}\n",
    "    else:\n",
    "        print(f'Example: {filename} already exists.')\n",
    "        \n",
    "    # Extract\n",
    "    folder_name = filename.replace('.zip', '')\n",
    "    extract_path = os.path.join(target_dir, folder_name)\n",
    "    if not os.path.exists(extract_path):\n",
    "        print(f'📦 Extracting {filename}...')\n",
    "        with zipfile.ZipFile(path, 'r') as zip_ref:\n",
    "            zip_ref.extractall(target_dir)\n",
    "    else:\n",
    "        print(f'✅ {folder_name} already extracted.')\n",
    "\n",
    "download_and_extract(FMA_SMALL_URL, DATA_ROOT)\n",
    "download_and_extract(FMA_META_URL, DATA_ROOT)\n",
    "\n",
    "print('📁 Data Ready.')"
]

# CELL 3: IMPORTS & CONFIG
cell_3_source = [
    "# ⚙️ Imports & Configuration\n",
    "# ==========================\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import torch.nn.functional as F\n",
    "import torchaudio\n",
    "import torchvision.models as models\n",
    "from torch.cuda.amp import GradScaler, autocast\n",
    "\n",
    "import numpy as np\n",
    "import librosa\n",
    "import pandas as pd\n",
    "import soundfile as sf\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import glob\n",
    "import time\n",
    "import random\n",
    "from tqdm.notebook import tqdm\n",
    "\n",
    "# --- CONFIGURATION ---\n",
    "class Config:\n",
    "    # Audio\n",
    "    SAMPLE_RATE = 22050\n",
    "    DURATION = 3.0  # Seconds per view\n",
    "    N_MELS = 128\n",
    "    N_FFT = 2048\n",
    "    HOP_LENGTH = 512\n",
    "    \n",
    "    # Training\n",
    "    BATCH_SIZE = 128        # Increase to 256 for A100\n",
    "    EPOCHS = 200            # Production run\n",
    "    LEARNING_RATE = 3e-4\n",
    "    TEMPERATURE = 0.5       # NT-Xent Temp\n",
    "    WEIGHT_DECAY = 1e-4\n",
    "    EMBEDDING_DIM = 2048    # ResNet50 Output\n",
    "    PROJECTION_DIM = 128    # SimCLR Projection\n",
    "    \n",
    "    # Hardware\n",
    "    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    NUM_WORKERS = 2         # Colab Usually has 2 cores\n",
    "    \n",
    "    # Paths\n",
    "    DATA_DIR = './data/fma_small'\n",
    "    METADATA_DIR = './data/fma_metadata'\n",
    "    CHECKPOINT_DIR = './checkpoints'\n",
    "\n",
    "os.makedirs(Config.CHECKPOINT_DIR, exist_ok=True)\n",
    "print(f'🔥 Running on {Config.DEVICE}')\n"
]

# CELL 4: AUGMENTATIONS
cell_4_source = [
    "# 🛠️ Augmentations (Goldilocks Protocol)\n",
    "# ======================================\n",
    "class AudioAugmentations:\n",
    "    def __init__(self, sample_rate):\n",
    "        self.sample_rate = sample_rate\n",
    "\n",
    "    def add_noise(self, audio, min_amp=0.1, max_amp=0.4):\n",
    "        \"\"\"Additive Gaussian Noise\"\"\"\n",
    "        noise_amp = np.random.uniform(min_amp, max_amp)\n",
    "        noise = np.random.randn(len(audio)) * noise_amp\n",
    "        return audio + noise\n",
    "\n",
    "    def add_reverb(self, audio):\n",
    "        \"\"\"Simulate Reverb via Decay\"\"\"\n",
    "        decay = np.exp(-np.linspace(0, 2, len(audio)))\n",
    "        noise = np.random.randn(len(audio)) * 0.2\n",
    "        return audio + (noise * decay)\n",
    "\n",
    "    def time_mask(self, spec, max_mask_pct=0.1):\n",
    "        \"\"\"Mask time steps in spectrogram\"\"\"\n",
    "        frames = spec.shape[2]\n",
    "        mask_width = int(frames * max_mask_pct)\n",
    "        start = random.randint(0, frames - mask_width)\n",
    "        spec[:, :, start:start+mask_width] = 0\n",
    "        return spec\n",
    "\n",
    "    def freq_mask(self, spec, max_mask_pct=0.1):\n",
    "        \"\"\"Mask frequency bands\"\"\"\n",
    "        freqs = spec.shape[1]\n",
    "        mask_height = int(freqs * max_mask_pct)\n",
    "        start = random.randint(0, freqs - mask_height)\n",
    "        spec[:, start:start+mask_height, :] = 0\n",
    "        return spec\n",
    "    \n",
    "    def __call__(self, audio, p=0.8):\n",
    "        # Waveform Augmentations\n",
    "        if random.random() < p:\n",
    "            if random.random() < 0.5: \n",
    "                audio = self.add_noise(audio)\n",
    "            else:\n",
    "                audio = self.add_reverb(audio)\n",
    "        return audio\n",
    "        \n",
    "    def apply_spec_augment(self, spec):\n",
    "        # Spectrogram Augmentations\n",
    "        if random.random() < 0.5:\n",
    "            spec = self.time_mask(spec)\n",
    "        if random.random() < 0.5:\n",
    "            spec = self.freq_mask(spec)\n",
    "        return spec\n"
]

# CELL 5: DATASET
cell_5_source = [
    "# 💾 Dataset Class\n",
    "# ================\n",
    "class FMAContrastiveDataset(Dataset):\n",
    "    def __init__(self, data_dir, duration=3.0, sample_rate=22050, transform=None):\n",
    "        self.data_dir = data_dir\n",
    "        self.sample_rate = sample_rate\n",
    "        self.duration = duration\n",
    "        self.n_samples = int(sample_rate * duration)\n",
    "        self.transform = transform\n",
    "        \n",
    "        print('🔍 Scanning files...')\n",
    "        self.files = glob.glob(os.path.join(data_dir, '**/*.mp3'), recursive=True)\n",
    "        # Filter out corrupted files if known list exists, otherwise ignore\n",
    "        print(f'✅ Found {len(self.files)} files.')\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.files)\n",
    "\n",
    "    def _load_audio(self, path):\n",
    "        try:\n",
    "            # Load full file\n",
    "            y, sr = librosa.load(path, sr=self.sample_rate, mono=True)\n",
    "            \n",
    "            # Pad if too short\n",
    "            if len(y) < self.n_samples:\n",
    "                padding = self.n_samples - len(y)\n",
    "                y = np.pad(y, (0, padding))\n",
    "            \n",
    "            # Random Crop\n",
    "            if len(y) > self.n_samples:\n",
    "                start = random.randint(0, len(y) - self.n_samples)\n",
    "                y = y[start:start+self.n_samples]\n",
    "            else:\n",
    "                y = y[:self.n_samples]\n",
    "                \n",
    "            return y\n",
    "        except Exception as e:\n",
    "            # Return silent array on error to keep batch consistent\n",
    "            return np.zeros(self.n_samples)\n",
    "\n",
    "    def _to_melspec(self, audio):\n",
    "        mels = librosa.feature.melspectrogram(\n",
    "            y=audio, \n",
    "            sr=self.sample_rate, \n",
    "            n_mels=128, \n",
    "            n_fft=2048, \n",
    "            hop_length=512\n",
    "        )\n",
    "        mels_db = librosa.power_to_db(mels, ref=np.max)\n",
    "        \n",
    "        # Normalize [-1, 1]\n",
    "        min_val, max_val = mels_db.min(), mels_db.max()\n",
    "        if max_val - min_val > 1e-6:\n",
    "            mels_db = (mels_db - min_val) / (max_val - min_val)\n",
    "            mels_db = mels_db * 2 - 1\n",
    "        else:\n",
    "            mels_db = np.zeros_like(mels_db)\n",
    "            \n",
    "        return torch.tensor(mels_db).unsqueeze(0).float() # (1, 128, T)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        path = self.files[idx]\n",
    "        \n",
    "        # Load raw audio\n",
    "        raw_audio = self._load_audio(path)\n",
    "        \n",
    "        # View 1: Augmented\n",
    "        v1_audio = raw_audio.copy()\n",
    "        if self.transform:\n",
    "            v1_audio = self.transform(v1_audio)\n",
    "        spec1 = self._to_melspec(v1_audio)\n",
    "        if self.transform:\n",
    "            spec1 = self.transform.apply_spec_augment(spec1)\n",
    "\n",
    "        # View 2: DIFFERENT Augmentation\n",
    "        v2_audio = raw_audio.copy()\n",
    "        if self.transform:\n",
    "            v2_audio = self.transform(v2_audio)\n",
    "        spec2 = self._to_melspec(v2_audio)\n",
    "        if self.transform:\n",
    "            spec2 = self.transform.apply_spec_augment(spec2)\n",
    "\n",
    "        return spec1, spec2\n"
]

# CELL 6: MODEL
cell_6_source = [
    "# 🧠 ResNet50 SimCLR Model\n",
    "# ========================\n",
    "class SimCLR(nn.Module):\n",
    "    def __init__(self, base_model='resnet50', embedding_dim=2048, projection_dim=128):\n",
    "        super().__init__()\n",
    "        \n",
    "        # Encoder\n",
    "        if base_model == 'resnet50':\n",
    "            self.encoder = models.resnet50(weights=None)\n",
    "            self.encoder.conv1 = nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)\n",
    "            prev_dim = self.encoder.fc.in_features\n",
    "            self.encoder.fc = nn.Identity() # Remove default FC\n",
    "        else:\n",
    "            raise NotImplementedError\n",
    "            \n",
    "        # Projection Head (MLP)\n",
    "        self.projector = nn.Sequential(\n",
    "            nn.Linear(prev_dim, prev_dim),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(prev_dim, projection_dim)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        h = self.encoder(x)\n",
    "        z = self.projector(h)\n",
    "        return h, z\n",
    "\n",
    "# Loss Function\n",
    "def nt_xent_loss(z1, z2, temperature=0.5):\n",
    "    # Z1, Z2: (B, D)\n",
    "    batch_size = z1.shape[0]\n",
    "    \n",
    "    # Normalize\n",
    "    z1 = F.normalize(z1, dim=1)\n",
    "    z2 = F.normalize(z2, dim=1)\n",
    "    \n",
    "    # Concat -> (2B, D)\n",
    "    z = torch.cat([z1, z2], dim=0)\n",
    "    \n",
    "    # Similarity Matrix (2B, 2B)\n",
    "    sim_matrix = torch.matmul(z, z.T) / temperature\n",
    "    \n",
    "    # Mask out self-similarity\n",
    "    mask = torch.eye(2 * batch_size, device=z.device).bool()\n",
    "    sim_matrix.masked_fill_(mask, -9e15)\n",
    "    \n",
    "    # Positive pairs: (i, i+B) and (i+B, i)\n",
    "    # We want sim(z[i], z[i+B]) to be high\n",
    "    \n",
    "    # Targets\n",
    "    labels = torch.cat([\n",
    "        torch.arange(batch_size, device=z.device) + batch_size,\n",
    "        torch.arange(batch_size, device=z.device)\n",
    "    ], dim=0)\n",
    "    \n",
    "    loss = F.cross_entropy(sim_matrix, labels)\n",
    "    return loss\n"
]

# CELL 7: TRAINING
cell_7_source = [
    "# 🏋️ Training Loop\n",
    "# ================\n",
    "def train():\n",
    "    # 1. Setup\n",
    "    augmenter = AudioAugmentations(Config.SAMPLE_RATE)\n",
    "    dataset = FMAContrastiveDataset(Config.DATA_DIR, transform=augmenter)\n",
    "    dataloader = DataLoader(\n",
    "        dataset, \n",
    "        batch_size=Config.BATCH_SIZE, \n",
    "        shuffle=True, \n",
    "        num_workers=Config.NUM_WORKERS,\n",
    "        pin_memory=True,\n",
    "        drop_last=True\n",
    "    )\n",
    "    \n",
    "    model = SimCLR(base_model='resnet50').to(Config.DEVICE)\n",
    "    optimizer = optim.Adam(model.parameters(), lr=Config.LEARNING_RATE, weight_decay=Config.WEIGHT_DECAY)\n",
    "    scaler = GradScaler() # AMP\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=Config.EPOCHS)\n",
    "\n",
    "    print(f'🚀 Starting Training for {Config.EPOCHS} Epochs...')\n",
    "    \n",
    "    loss_history = []\n",
    "    \n",
    "    for epoch in range(Config.EPOCHS):\n",
    "        model.train()\n",
    "        total_loss = 0\n",
    "        start_time = time.time()\n",
    "        \n",
    "        pbar = tqdm(dataloader, desc=f'Epoch {epoch+1}/{Config.EPOCHS}', leave=False)\n",
    "        \n",
    "        for batch in pbar:\n",
    "            spec1, spec2 = batch\n",
    "            spec1, spec2 = spec1.to(Config.DEVICE), spec2.to(Config.DEVICE)\n",
    "            \n",
    "            # Mixed Precision Forward\n",
    "            with autocast():\n",
    "                _, z1 = model(spec1)\n",
    "                _, z2 = model(spec2)\n",
    "                loss = nt_xent_loss(z1, z2, temperature=Config.TEMPERATURE)\n",
    "                \n",
    "            # Backward\n",
    "            optimizer.zero_grad()\n",
    "            scaler.scale(loss).backward()\n",
    "            scaler.step(optimizer)\n",
    "            scaler.update()\n",
    "            \n",
    "            total_loss += loss.item()\n",
    "            pbar.set_postfix({'loss': f'{loss.item():.4f}'})\n",
    "            \n",
    "        avg_loss = total_loss / len(dataloader)\n",
    "        loss_history.append(avg_loss)\n",
    "        scheduler.step()\n",
    "        \n",
    "        time_taken = time.time() - start_time\n",
    "        print(f'Epoch {epoch+1} | Loss: {avg_loss:.4f} | Time: {time_taken:.1f}s')\n",
    "        \n",
    "        # Save Checkpoint every 10 epochs\n",
    "        if (epoch + 1) % 10 == 0:\n",
    "            ckpt_path = os.path.join(Config.CHECKPOINT_DIR, f'resnet50_e{epoch+1}.pt')\n",
    "            torch.save({\n",
    "                'epoch': epoch,\n",
    "                'model_state_dict': model.state_dict(),\n",
    "                'optimizer_state_dict': optimizer.state_dict(),\n",
    "                'loss': avg_loss,\n",
    "            }, ckpt_path)\n",
    "            print(f'💾 Saved checkpoint: {ckpt_path}')\n",
    "            \n",
    "    # Plot Loss\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    plt.plot(loss_history)\n",
    "    plt.title('Training Loss (SimCLR ResNet50)')\n",
    "    plt.xlabel('Epoch')\n",
    "    plt.ylabel('NT-Xent Loss')\n",
    "    plt.show()\n",
    "    \n",
    "    return model\n",
    "\n",
    "# Run\n",
    "if __name__ == '__main__':\n",
    "    trained_model = train()\n"
]

# JSON STRUCTURE
notebook_json = {
    "cells": [
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_1_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_2_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_3_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_4_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_5_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_6_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_7_source}
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(OUTPUT_FILE, 'w') as f:
    json.dump(notebook_json, f, indent=2)

print(f"Created {OUTPUT_FILE}")
